### ISSUE TITLE
Add a Valve operator

### ISSUE THREAD

**Issue by Glurt** [akarnokd/RxJava2Extensions#1]
Similar to the operator you created for Rx 1: https://gist.github.com/akarnokd/1c54e5a4f64f9b1e46bdcf62b4222f08

Most reactive extensions for other languages can achieve something similar using various operators in combination but I'm struggling to recreate it in RxJava, I'm also struggling to convert the above operator into Rx 2.x to use it personally.

The goal is to be able to trigger the valve to open or close using a boolean value, when open the stream should flow as normal, when closed the items are buffered until the valve is opened again, where all buffered items are then emitted. I can see this being quite useful for a number of reasons so I was hoping it could become officially supported.

**Comment by akarnokd** [comment]
Closing via [0.7.2](https://github.com/akarnokd/RxJava2Extensions/releases/tag/v0.7.2). May take some time to show up on maven central but you can point your maven to sonatype's public repository.

**Comment by Glurt** [comment]
That was quick! Thanks for the work, I'll take a look now.

**Comment by Glurt** [comment]
Do you think it's worth adding valve for Completable, Maybe, and Single? I know that the typical usecase is to stem a stream of events but I'd like to be able to delay the subscriber (onNext, onError, onComplete) being called until the valve is opened.

**Comment by akarnokd** [comment]
Look a the `delaySubscription` operator.

**Comment by Glurt** [comment]
How could it be used to delay indefinitely, rather than a specified period of time? I'm using the valve to pause when the Activity pauses and resume when the Activity resumes, there's no way of knowing how long the Activity will be paused for.

**Comment by Glurt** [comment]
Ok so delaySubscription isn't quite what I'm wanting. delaySubscription just prevents the sequence from executing until a second Publisher emits a value.

This means that when the Activity is resumed the sequence is subscribed and starts processing but if the Activity is paused again the sequence doesn't pause like it does with valve.

**Comment by akarnokd** [comment]
Convert to flowable and back to the original type.

**Comment by Glurt** [comment]
Sure, I can do that.

If you decide to add them in future could you update this issue?

**Comment by akarnokd** [comment]
Sure.

**Comment by guliash** [comment]
I succeeded in creating Valve using default RxJava operators:
```
final Random random = new Random();
        final Observable<Boolean> gates = Observable.interval(10, TimeUnit.SECONDS)
                .map(it -> random.nextBoolean())
                .startWith(false)
                .doOnNext(it -> System.out.println("Gate " + (it ? "opened" : "closed")))
                .take(100);
        final Observable<Long> data = Observable.interval(3, TimeUnit.SECONDS)
                .doOnNext(it -> System.out.println("New value " + it))
                .take(100);

        gates.publish(innerGates -> data.publish(innerData -> Observable.merge(
                innerData.window(
                        innerGates.distinctUntilChanged().filter(it -> it),
                        (ignore -> innerGates.distinctUntilChanged().filter(it -> !it))
                ).flatMap(it -> it),
                innerData.buffer(
                        innerGates.distinctUntilChanged().filter(it -> !it),
                        (ignore -> innerGates.distinctUntilChanged().filter(it -> it))
                )
                        .flatMap(Observable::from)
        )))
                .subscribe(it -> System.out.println("On next " + it));
```

The idea is that between open-close we use window and buffer between close-open.

**Comment by akarnokd** [comment]
The more operators are involved the greater chance there is a race and unwanted delays in open-close. The [FlowableValve](https://github.com/akarnokd/RxJava2Extensions/blob/master/src/main/java/hu/akarnokd/rxjava2/operators/FlowableValve.java) does it well with the shortest paths.
