### ISSUE TITLE
RxJavaAssemblyException Doesn't Show Stack Trace

### ISSUE THREAD

**Issue by T-Spoon** [akarnokd/RxJava2Extensions#10]
I noticed some differences in between `RxJavaAssemblyException` and RxJava1's `AssemblyStackTraceException`, namely that the the current implementation doesn't pass the stacktrace as a message to super [here](https://github.com/akarnokd/RxJava2Extensions/blob/master/src/main/java/hu/akarnokd/rxjava2/debug/RxJavaAssemblyException.java#L31). 

This makes it somewhat difficult to track call sites of streams (without having a debugger attached all the time, or adding some custom logger implementation to specifically log these types of exceptionsusing the `find` method)

Is this by design?  Maybe for clarity when dealing with many chained exceptions?  

You also mentioned in the readme that the format is up for discussion - does this mean we'll see support for this in the main RxJava2 repo at some point?

Happy to submit a PR if there's any work needed here (maybe some flags to set what level of logging a user would like e.g. `SHOW_ALL_STACKTRACES`, `SHOW_LAST_STACKTRACE`, `HIDE_ALL_STACKTRACES`).

**Comment by akarnokd** [comment]
> Is this by design?

The v2 design was primary for debugging sessions but I guess the stacktrace could go into the message part instead.

> does this mean we'll see support for this in the main RxJava2 repo at some point?

The problem with the v1 version is that different people imagine different structure. To avoid arguing, v2 doesn't have this in RxJava proper but I have a version I can work with in this repo.

>  (maybe some flags to set what level of logging a user would like e.g. SHOW_ALL_STACKTRACES, SHOW_LAST_STACKTRACE, HIDE_ALL_STACKTRACES)

As mentioned, many people want many features and structure. I encourage you to roll your own based on this repo and you can make it as you see fit.

**Comment by T-Spoon** [comment]
Ah, thanks for the info!  

I took your advice and created a small library to suit my needs a little better: https://github.com/T-Spoon/Traceur
