### ISSUE TITLE
Remove deprecated extensions

### ISSUE THREAD

**Issue by veyndan** [akarnokd/RxJava2Extensions#11]
As per the `README`, the following should be removed from the library as RxJava 2.1 has been released:

* [Parallel operations](https://github.com/akarnokd/RxJava2Extensions#parallel-operations)
* [`SingleSubject`, `MaybeSubject` and `CompletableSubject`](https://github.com/akarnokd/RxJava2Extensions#singlesubject-maybesubject-and-completablesubject)

**Comment by akarnokd** [comment]
Thanks. Done.
