### ISSUE TITLE
SingleConsumers.subscribeAutoDispose does not always remove the Disposable from the CompositeDisposable

### ISSUE THREAD

**Issue by dano** [akarnokd/RxJava2Extensions#27]
I'm not sure if I'm actually just misunderstanding how `subscribeAutoDispose` is supposed to work or if this is a bug - basically, if I use `SingleConsumers.subscribeAutoDispose`, and the `Single` I pass in completes via `onSuccess`, it does not get removed from the `CompositeDisposable`. It seems like this is because `DisposableAutoReleaseMultiObserver.onSuccess` does not call `removeSelf()`. I think `MaybeConsumers.subscribeAutoDispose` has the same behavior. But again, I'm not sure if this is a real bug or I'm just misunderstanding something.

**Comment by akarnokd** [comment]
It should, but the tests have copy-paste errors and I overlooked this. Would you like to post a PR?
