### ISSUE TITLE
Specify exact buffer size to Unicast-/DispatchWorkSubject

### ISSUE THREAD

**Issue by wrozwad** [akarnokd/RxJava2Extensions#60]
Using `UnicastWorkSubject`, `DispatchWorkSubject` or `DispatchWorkProcessor` with `create(Int)` function we can specify "hint" capacity size. Buf if I want to buffer only the last item and receive them in `onSubscribe()` then `create(1)` doesn't work as intendent - I still receive many of cached events. Is there any other way to do that?

**Comment by akarnokd** [comment]
No. Those classes have been designed to deliver all events. 

Why don't you use `BehaviorSubject` instead?

**Comment by wrozwad** [comment]
Because I need to consume events after delivery - what `UnicastSubject` do :)

**Comment by akarnokd** [comment]
Makes no sense. The work subject buffers signals so that when one consumer leaves, the next one can resume with the unconsumed and future items. 

`BehaviorSubject` holds the very last item only. If a consumer leaves, all inbetween items except the latest will be essentially ignored. A new consumer then receives the very last item.

**Comment by wrozwad** [comment]
But what I need is some `*Subject` that consume the last event if it's delivered to any subscriber. Some like this:

1. You pass few messages to `*Subject`
2. You open a screen where you want to display only the last message
3. You leave this screen for a while
4. When you back to the screen you don't want to receive and display the same messages once again

**Comment by akarnokd** [comment]
Still use a `BeaviorSubject` and add a flag to the message saying `consumed`, then filter out messages with that flag set.

**Comment by wrozwad** [comment]
Yes, this is the only workaround that I can found :/
